spring.datasource.url=${NEV_DB_URL:jdbc:postgresql://localhost:5432/neverest}
spring.datasource.username=${NEV_DB_USER:postgres}
spring.datasource.password=${NEV_DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
