spring.datasource.url=${NEV_DB_URL:jdbc:postgresql://localhost:5432/neverest}
spring.datasource.username=${NEV_DB_USER:postgres}
spring.datasource.password=${NEV_DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.type.preferred_uuid_jdbc_type=CHAR
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
